# Generated by Django 4.0.6 on 2022-09-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('audio_md5', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='主键，音频md5值')),
                ('audio_path', models.CharField(max_length=200, verbose_name='音频文件名')),
                ('emotion_tag', models.CharField(max_length=20, verbose_name='标签')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_md5', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='主键，视频md5值')),
                ('video_path', models.CharField(max_length=200, verbose_name='视频文件名')),
            ],
            options={
                'db_table': 'video',
            },
        ),
    ]
