# Generated by Django 4.0.6 on 2022-07-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_md5', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='主键，视频md5值')),
                ('video_name', models.CharField(max_length=200, verbose_name='视频文件名')),
            ],
            options={
                'db_table': 'video',
            },
        ),
    ]
