# Generated by Django 4.0.6 on 2022-09-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='emotion_tag',
            field=models.CharField(max_length=20, null=True, verbose_name='标签'),
        ),
    ]
