# Generated by Django 4.0.6 on 2022-09-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_audio_emotion_tag'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='audio',
            table='audio',
        ),
    ]
